language: php

php:
  - 5.3
  - 5.4

before_script:
  - cd libuv && make uv.a CFLAGS=-fPIC -s && cd ..
  - phpize && ./configure && make && sudo make install
  - echo "extension=uv.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#php-uv"
    skip_join: true
    use_notice: true 
