language: php

php:
  - 5.3
  - 5.4

before_script:
    - cd libuv && make -s && cd ..
    - phpize && ./configure && make && sudo make install
    - echo "extension=uv.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`