language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - chmod +x travis-install.sh

install: ./travis-install.sh

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#php-uv"
    skip_join: true
    use_notice: true 
